
book_info = {
		"'Munpiilee Gbangu": { "id" : "GEN", "file_name" : "01_Genesis.usfm" },
		"'Yiibu Gbangu": { "id" : "EXO", "file_name" : "02_Exodus.usfm" },
		"'Liivai Gbangu": { "id" : "LEV", "file_name" : "03_Leviticus.usfm" },
		"Soribu Gbangu": { "id" : "NUM", "file_name" : "04_Numbers.usfm" },
		"Duturoonomi Gbangu": { "id" : "DEU", "file_name" : "05_Deuteronomy.usfm" },
		"'Joosua Gbangu": { "id" : "JOS", "file_name" : "06_Joshua.usfm" },
		"Saringmaariba Gbangu": { "id" : "JDG", "file_name" : "07_Judges.usfm" },
		"'Ruut Gbangu": { "id" : "RUT", "file_name" : "08_Ruth.usfm" },
		"Fora Saamiu-el Gbangu": { "id" : "1SA", "file_name" : "09_1_Samuel.usfm" },
		"'Yiilung Saamiu-el Gbangu": { "id" : "2SA", "file_name" : "10_2_Samuel.usfm" },
		"Fora Na'mine Gbangu": { "id" : "1KI", "file_name" : "11_1_Kings.usfm" },
		"'Yiilung Na'mine Gbangu": { "id" : "2KI", "file_name" : "12_2_Kings.usfm" },
		"Fora Tung'kori Gbangu": { "id" : "1CH", "file_name" : "13_1_Chronicles.usfm" },
		"'Yiilung Tung'kori Gbangu": { "id" : "2CH", "file_name" : "14_2_Chronicles.usfm" },
		"Eezira Gbangu": { "id" : "EZR", "file_name" : "15_Ezra.usfm" },
		"'Niihemaiya Gbangu": { "id" : "NEH", "file_name" : "16_Nehemiah.usfm" },
		"Eesiter Gbangu": { "id" : "EST", "file_name" : "17_Esther.usfm" },
		"'Joob Gbangu": { "id" : "JOB", "file_name" : "18_Job.usfm" },
		"'Yieme Gbangu": { "id" : "PSA", "file_name" : "19_Psalms.usfm" },
		"Yeng Yeli'bie Gbangu": { "id" : "PRO", "file_name" : "20_Proverbs.usfm" },
		"Ikilisiasitiz Gbangu": { "id" : "ECC", "file_name" : "21_Ecclesiastes.usfm" },
		"Soolomong 'Yienii Gbangu": { "id" : "SNG", "file_name" : "22_Song_of_Solomon.usfm" },
		"Ai'zeeya Gbangu": { "id" : "ISA", "file_name" : "23_Isaiah.usfm" },
		"Jeremaiya Gbangu": { "id" : "JER", "file_name" : "24_Jeremiah.usfm" },
		"Jeremaiya Laa'dimii Gbangu": { "id" : "LAM", "file_name" : "25_Lamentations.usfm" },
		"'Iziiki-el Gbangu": { "id" : "EZK", "file_name" : "26_Ezekiel.usfm" },
		"Daaniel Gbangu": { "id" : "DAN", "file_name" : "27_Daniel.usfm" },
		"'Hozeeya Gbangu": { "id" : "HOS", "file_name" : "28_Hosea.usfm" },
		"'Joo-el Gbangu": { "id" : "JOL", "file_name" : "29_Joel.usfm" },
		"'Eemos Gbangu": { "id" : "AMO", "file_name" : "30_Amos.usfm" },
		"'Obadaiya Gbangu": { "id" : "OBA", "file_name" : "31_Obadiah.usfm" },
		"'Joona Gbangu": { "id" : "JON", "file_name" : "32_Jonah.usfm" },
		"Maika Gbangu": { "id" : "MIC", "file_name" : "33_Micah.usfm" },
		"'Nee-hum Gbangu": { "id" : "NAM", "file_name" : "34_Nahum.usfm" },
		"Habaakuk Gbangu": { "id" : "HAB", "file_name" : "35_Habakkuk.usfm" },
		"Zefanaiya Gbangu": { "id" : "ZEP", "file_name" : "36_Zephaniah.usfm" },
		"Haagai Gbangu": { "id" : "HAG", "file_name" : "37_Haggai.usfm" },
		"Zekaraiya Gbangu": { "id" : "ZEC", "file_name" : "38_Zechariah.usfm" },
		"Maalakai Gbangu": { "id" : "MAL", "file_name" : "39_Malachi.usfm" },
		"'Maatiu Gbangu": { "id" : "MAT", "file_name" : "40_Matthew.usfm" },
		"Maaki Gbangu": { "id" : "MRK", "file_name" : "41_Mark.usfm" },
		"'Luki Gbangu": { "id" : "LUK", "file_name" : "42_Luke.usfm" },
		"Joon Gbangu": { "id" : "JHN", "file_name" : "43_John.usfm" },
		"A 'Bi-tunihi Tuma Gbangu": { "id" : "ACT", "file_name" : "44_Acts.usfm" },
		"'Rom Gbangu": { "id" : "ROM", "file_name" : "45_Romans.usfm" },
		"Fora Korinti Gbangu": { "id" : "1CO", "file_name" : "46_1_Corinthians.usfm" },
		"'Yiilung Korinti Gbangu": { "id" : "2CO", "file_name" : "47_2_Corinthians.usfm" },
		"'Galeetiya Gbangu": { "id" : "GAL", "file_name" : "48_Galatians.usfm" },
		"Eefesus Gbangu": { "id" : "EPH", "file_name" : "49_Ephesians.usfm" },
		"Filiipai Gbangu": { "id" : "PHP", "file_name" : "50_Philippians.usfm" },
		"Koloosi Gbangu": { "id" : "COL", "file_name" : "51_Colossians.usfm" },
		"Fora Tesalonaika Gbangu": { "id" : "1TH", "file_name" : "52_1_Thessalonians.usfm" },
		"'Yiilung Tesalonaika Gbangu": { "id" : "2TH", "file_name" : "53_2_Thessalonians.usfm" },
		"Fora Tiimoti Gbangu": { "id" : "1TI", "file_name" : "54_1_Timothy.usfm" },
		"'Yiilung Tiimoti Gbangu": { "id" : "2TI", "file_name" : "55_2_Timothy.usfm" },
		"Taitus Gbangu": { "id" : "TIT", "file_name" : "56_Titus.usfm" },
		"'Failiimong Gbangu": { "id" : "PHM", "file_name" : "57_Philemon.usfm" },
		"'Hiiburihi Gbangu": { "id" : "HEB", "file_name" : "58_Hebrews.usfm" },
		"'Jeemes Gbangu": { "id" : "JAS", "file_name" : "59_James.usfm" },
		"Fora 'Pii-ter Gbangu": { "id" : "1PE", "file_name" : "60_1_Peter.usfm" },
		"'Yiilung 'Pii-ter Gbangu": { "id" : "2PE", "file_name" : "61_2_Peter.usfm" },
		"Fora Joon Gbangu": { "id" : "1JN", "file_name" : "62_1_John.usfm" },
		"'Yiilung Joon Gbangu": { "id" : "2JN", "file_name" : "63_2_John.usfm" },
		"Taalung Joon Gbangu": { "id" : "3JN", "file_name" : "64_3_John.usfm" },
		"'Juud Gbangu": { "id" : "JUD", "file_name" : "65_Jude.usfm" },
		"'Yesu 'Kristo Yeli'yuoruu Gbangu": { "id" : "REV", "file_name" : "66_Revelation.usfm" },
	}
